name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            **/*.md
            !node_modules
        continue-on-error: true
      - name: Link check
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --max-concurrency 4 './**/*.md'
          fail: false
